name: Bug report (Quasar v2)
description: Create a report to help us improve
labels: ['🐞 bug', '🔝 Qv2']

body:
  - type: markdown
    attributes:
      value: |
        ### Read Before Proceeding Further

        This form is for submitting a **bug report** for Quasar Framework(**v2**).
        So, if you are using another version, just seeking help, or want to submit a feature request, please return back and choose a more suitable option from the list. 

        Also, please search your issue on the repo and make sure it does not already exist.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly and concisely explain the problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: repro-link
    attributes:
      label: Codepen/jsFiddle/Codesandbox Link
      description: Fork a [Codepen](https://codepen.quasar.dev) or a [jsFiddle](https://jsfiddle.quasar.dev) or a [Codesandbox](https://codesandbox.quasar.dev) and hit save then copy-paste the link here.
    validations:
      required: true
  - type: textarea
    id: repro-description
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior.
      value: |
        1. Go to the provided reproduction link
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true
  - type: dropdown
    id: areas
    attributes:
      label: Areas
      description: Mark the areas in which you see the problem on.
      multiple: true
      options:
        - Quasar CLI
        - Components/Directives/Plugins
        - Quasar Extras
        - SPA Mode
        - SSR Mode
        - PWA Mode
        - Electron Mode
        - Cordova Mode
        - Capacitor Mode
        - BEX Mode
        - TypeScript Support
        - Icon Genie CLI
        - App Extension API
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Platforms/Browsers
      description: Mark the platforms/browsers in which you see the problem on. _If you select `Other`, please explain it in `Additional context` section._
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - iOS
        - Android
        - Electron
        - Other
  - type: textarea
    id: q-info
    attributes:
      label: Quasar info output
      description: Please run [`quasar info` command](https://quasar.dev/quasar-cli/commands-list#info), then copy and paste the output.
      render: shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. _This will be automatically formatted into code, so no need for backticks._
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
